version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
      - aws-s3/sync:
        arguments: |
          --acl public-read \
          --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: ./public
          overwrite: true
          to: 's3://awssaintbucket/?region=us-east-2'
      - aws-s3/copy:
          arguments: '--dry-run'
          from: ./public
          to: 's3://awssaintbucket'          
workflows:
    build:
      jobs:
        - build
